name: Checks
on:
  pull_request:
    branches:
      - main
jobs:
  check-sync-doc:
    name: Check Sync README doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1
      - run: .script/check-sync-doc.sh
  doctest:
    name: Doctest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1
      - run: yarn test
  version:
    name: Check bump of package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: .script/check-bump-version.sh
  build:
    name: Check if build is ok
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1
      - run: yarn build

